execute if score mrg_kyukurarin mrg_music matches 1.. run function minecraft_rythm_game:music/kyukurarin/music

function minecraft_rythm_game:rythm_game/key_detection
function minecraft_rythm_game:rythm_game/button_animation
function minecraft_rythm_game:rythm_game/notes_drop