execute if score mrg_kyukurarin_notes mrg_music matches 0 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 12 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 24 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 36 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 48 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 60 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 72 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 84 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 96 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 108 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 120 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 132 run function minecraft_rythm_game:rythm_game/note_summon/lane0
