execute if score mrg_kyukurarin_notes mrg_music matches 48 run function minecraft_rythm_game:rythm_game/note_summon/lane3
execute if score mrg_kyukurarin_notes mrg_music matches 51 run function minecraft_rythm_game:rythm_game/note_summon/lane2
execute if score mrg_kyukurarin_notes mrg_music matches 54 run function minecraft_rythm_game:rythm_game/note_summon/lane1
execute if score mrg_kyukurarin_notes mrg_music matches 57 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 60 run function minecraft_rythm_game:rythm_game/note_summon/lane3
execute if score mrg_kyukurarin_notes mrg_music matches 63 run function minecraft_rythm_game:rythm_game/note_summon/lane2
execute if score mrg_kyukurarin_notes mrg_music matches 66 run function minecraft_rythm_game:rythm_game/note_summon/lane1
execute if score mrg_kyukurarin_notes mrg_music matches 69 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 72 run function minecraft_rythm_game:rythm_game/note_summon/lane3
execute if score mrg_kyukurarin_notes mrg_music matches 75 run function minecraft_rythm_game:rythm_game/note_summon/lane2
execute if score mrg_kyukurarin_notes mrg_music matches 78 run function minecraft_rythm_game:rythm_game/note_summon/lane1
execute if score mrg_kyukurarin_notes mrg_music matches 81 run function minecraft_rythm_game:rythm_game/note_summon/lane0
execute if score mrg_kyukurarin_notes mrg_music matches 84 run function minecraft_rythm_game:rythm_game/note_summon/lane3
execute if score mrg_kyukurarin_notes mrg_music matches 87 run function minecraft_rythm_game:rythm_game/note_summon/lane2
execute if score mrg_kyukurarin_notes mrg_music matches 90 run function minecraft_rythm_game:rythm_game/note_summon/lane1
execute if score mrg_kyukurarin_notes mrg_music matches 93 run function minecraft_rythm_game:rythm_game/note_summon/lane0
